import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
	let [src, setSrc] = useState('/dallimage.jpeg');

	function generateImg() {
		const windowUrl = window.location.search;
		const params = new URLSearchParams(windowUrl);
		let userId = params.get('user');
		let description = document.getElementById('description').value;

		console.time();
		if (description !== '') {
			fetch(`/api/hello?q=${description}&user=${userId}`)
				.then((res) => res.json())
				.then((data) => {
					console.timeLog();
					setSrc(data.imgUrl);
				});
		}
	}
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <span>Dall E</span>
				</h1>

				<p className={styles.description}>
					Enter a description to generate a image
					{/* <code className={styles.code}>pages/index.js</code> */}
				</p>
				<input
					id="description"
					className={styles.input}
					type={'text'}
					placeholder="Enter Image description"
				/>
				<button className={styles.button} onClick={generateImg}>
					Generate
				</button>
				<div className={styles.grid}>
					<img src={src} className={[styles.img, styles.card].join(' ')} />
					<div className={styles.card}>
						<h2> Dog standing in a feild pixeled image</h2>
					</div>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer">
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src="/openailogo.png"
							alt="Open AI Logo"
							width={16}
							height={16}
							style={{ marginRight: 10 }}
						/>
					</span>
					Open AI
				</a>
			</footer>
		</div>
	);
}
